# Generated by Django 5.1 on 2024-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.TextField(max_length=120)),
                ('numero', models.CharField(max_length=6)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.TextField(max_length=100)),
            ],
        ),
    ]
