# Generated by Django 5.1 on 2024-09-09 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('001', 'Banco do Brasil S.A.'), ('021', 'Banestes S.A.')], default='', max_length=3)),
                ('num_conta', models.IntegerField()),
                ('saldo_conta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contas_receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('cliente', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Contas_pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.doc_entrada')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Mov_bancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('entradas', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('saidas', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('saldo_periodo', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('conta_bancaria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.conta_bancaria')),
            ],
        ),
    ]
