# Generated by Django 5.1 on 2024-09-02 17:28

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.CharField(max_length=6, unique=True)),
                ('nm_dep', models.CharField(max_length=25)),
                ('descricao', models.TextField(max_length=100)),
            ],
        ),
    ]
