# Generated by Django 5.1 on 2024-09-02 20:14
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dp_rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cargo', models.CharField(blank=True, max_length=6, unique=True)),
                ('nm_funcao', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=50)),
                ('sal_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_rh.departamento')),                
                
            ],
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cod_dep',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
