# Generated by Django 5.1 on 2024-09-04 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('dp_rh', '0002_cargo_alter_departamento_cod_dep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_funci', models.CharField(blank=True, max_length=6, unique=True)),
                ('nm_funcionario', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('dt_nasc', models.DateField()),
                ('nacionalidade', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_admissao', models.DateField()),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('cargo_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_rh.cargo')),
                ('depart_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp_rh.departamento')),
                ('end_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.endereco')),
            ],
        ),
    ]
