# Generated by Django 5.1 on 2024-08-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.CharField(max_length=6)),
                ('descricao', models.TextField(max_length=100)),
                ('un_medida', models.CharField(choices=[('UN', 'Unidade'), ('G', 'Grama'), ('KG', 'Quilo'), ('T', 'Tonelada'), ('L', 'Litro'), ('CM', 'Centímetro'), ('M', 'Metro')], default='UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_forn', models.CharField(max_length=6)),
                ('nm_fantasia', models.CharField(max_length=150)),
                ('rz_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14)),
                ('ie', models.CharField(max_length=11, null=True)),
                ('nm_contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('telefone', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('end_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=6)),
                ('emissao', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ped_compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='compras.pedido_compras')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_est', models.FloatField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.IntegerField()),
                ('serie_nt', models.CharField(max_length=3)),
                ('dt_emissao', models.DateField()),
                ('tipo_nf', models.CharField(choices=[('NFE', 'NF-e'), ('NFS', 'NFS'), ('CTE', 'CT-e')], default='', max_length=3)),
                ('cond_pgto', models.CharField(choices=[('001', 'A vista'), ('002', '7 dias'), ('003', '30 dias'), ('020', '30,60'), ('021', '30,60,90')], default='', max_length=3)),
                ('forma_pgto', models.CharField(choices=[('R$', 'Dinheiro'), ('PIX', 'Pix'), ('CD', 'Cartao Devito'), ('CC', 'Cartao Credito')], default='', max_length=3)),
                ('vencimento', models.DateField()),
                ('qtd_item', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cod_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedor')),
                ('item_nf_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.produto')),
            ],
        ),
    ]
