# Generated by Django 5.1 on 2024-08-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cod_prod', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('descricao', models.TextField(max_length=100)),
                ('un_medida', models.CharField(choices=[('UN', 'Unidade'), ('G', 'Grama'), ('KG', 'Quilo'), ('T', 'Tonelada'), ('L', 'Litro'), ('CM', 'Centímetro'), ('M', 'Metro')], default='UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_forn', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('nm_fantasia', models.CharField(max_length=150)),
                ('rz_social', models.CharField(max_length=150)),
                ('nm_contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('telefone', models.CharField(max_length=16)),
                ('cnpj', models.CharField(max_length=14)),
                ('end_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_compras',
            fields=[
                ('pedido', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('emissao', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ped_compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pedido_compras')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_est', models.FloatField(max_length=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.produto')),
            ],
        ),
    ]
