# Generated by Django 5.1 on 2024-09-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cod_forn',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
