# Generated by Django 5.1 on 2024-08-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nota', models.IntegerField()),
                ('serie_nt', models.CharField(max_length=3)),
                ('dt_emissao', models.DateField()),
                ('tipo_nf', models.CharField(choices=[('NFE', 'nota fiscal eletronia'), ('NFS', 'nota fiscal servico'), ('CTE', 'conhecimento transporte')], default='', max_length=3)),
                ('cod_forn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedor')),
                ('item_nf_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.produto')),
            ],
        ),
    ]
