# Generated by Django 5.1 on 2024-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_doc_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_entrada',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='doc_entrada',
            name='qtd_item',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doc_entrada',
            name='tipo_nf',
            field=models.CharField(choices=[('NFE', 'NF-e'), ('NFS', 'NFS'), ('CTE', 'CT-e')], default='', max_length=3),
        ),
    ]
