# Generated by Django 5.1 on 2024-08-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_fornecedor_cod_forn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='saldo_est',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item_pedido_compras',
            name='ped_compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedido_compras'),
        ),
        migrations.AlterField(
            model_name='item_pedido_compras',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
