# Generated by Django 5.1 on 2024-08-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_doc_entrada_preco_unitario_doc_entrada_qtd_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_entrada',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
