# Generated by Django 5.1 on 2024-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_estoque_saldo_est_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='ie',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
